-- AlterTable
ALTER TABLE "UserCarriere" ADD COLUMN     "derniereMajBesoins" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "energie" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "faim" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "moral" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN     "social" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN     "traits" JSONB;
